### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by KarlKaise** [aicb-ZhangLabs/Impeller#2]
Hello, 

I followed your dependencies instructions installation but came across following issue while installing torch-sparse==0.6.8

 pip install torch-sparse==0.6.16
Collecting torch-sparse==0.6.16
  Using cached torch_sparse-0.6.16.tar.gz (34 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/setup.py", line 7, in <module>
          import torch
        File "/site-packages/torch/__init__.py", line 202, in <module>
          from torch._C import *  # noqa: F403
      ImportError:/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

Would appreciate any help. Thanks
!

**Comment by KarlKaise** [comment]
Resolved by installing via mamba install -c conda-forge pytorch_sparse=0.6.16

Thank you
